!!de.appdynamics.extensions.snmpMonitor.cfg.SnmpTrapMonitorConfig
endpointConfig:
  SNMPV2Enable: true
  SNMPV3Enable: false
  SNMPv1Enable: true
  listenerAddress: 0.0.0.0
  listenerPort: 1026
traps:
  .1.2.3.2.3.4.2.3.4.2.1.2502: {}
  .1.2.3.2.3.4.2.3.4.2.1.2501: {}
  .1.2.3.2.3.4.2.3.4.2.1.2500: {}