!!de.appdynamics.extensions.snmpMonitor.cfg.SnmpTrapMonitorConfig
endpointConfig:
  SNMPV2Enable: true
  SNMPV3Enable: false
  SNMPv1Enable: true
  listenerAddress: 0.0.0.0
  listenerPort: 1026
traps:
  VCopAnomalActivity_start:
    path: VCOP|##1.3.6.1.4.1.6876.4.5.1.2.2##|AnomalyActive
    oid: 1.3.6.1.4.1.6876.4.5.1.0.22
    persistentValue: 1
  VCopAnomalActivity_clear:
      path: VCOP|##1.3.6.1.4.1.6876.4.5.1.2.2##|AnomalyActive
      oid: 1.3.6.1.4.1.6876.4.5.1.0.23
      persistentValue: 0
  VCopAnomalyCount_count:
      path: VCOP|AnomalyActive
      oid: 1.3.6.1.4.1.6876.4.5.1.0.13
  VCenterTest:
        path: VC|Test|##1.3.6.1.4.1.6876.4.3.307##|VCAlerts
        oid: 1.3.6.1.4.1.6876.4.3.0.203
        persistentFilter:
             oid: 1.3.6.1.4.1.6876.4.3.305
             defaultValue: 0
             filterElements:
             - filter: Green
               value: 0
             - filter: Red
               value: 2
             - filter: Yellow
               value: 1




